spring.application.name=qr_code
# Serveur
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/generateQrCode
spring.datasource.username=postgres
spring.datasource.password=jinx17
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols=
jwt.expiration=86400000
# 86400000 ms = 24 heures

# Taille max des fichiers (pour le logo)
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB