spring.application.name=qr_code
spring.profiles.active=dev

# Taille max des fichiers (pour le logo)
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

app.upload-dir=uploads/qrcodes

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
